apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-user-crud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-user-crud
  template:
    metadata:
      labels:
        app: grpc-user-crud
    spec:
      containers:
      - name: grpc-user-crud
        image: krishna03032003/grpc_user_crud:02
        ports:
        - containerPort: 50052
        env:
        - name: MONGODB_URL
          value: "mongodb+srv://admin:admin@cluster0.x4pzq.mongodb.net/"