apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: gcr.io/fluted-cogency-434512-n4/grpc_user_crud-grpc_server:latest
        ports:
        - containerPort: 50052
        env:
        - name: MONGODB_URL
          value: "mongodb+srv://admin:admin@cluster0.x4pzq.mongodb.net/"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 50052
    targetPort: 50052
  selector:
    app: grpc-server
